### PR TITLE
Add new references

### PR DESCRIPTION
**Pull request by koalive**
Hi! I added quite a few references and I'd be happy to get feedback.
I believe these additions would be relevant for the community, but I also stumbled upon a few articles for which I was not sure they would meet the repository criteria (see #11). If by any chance you see something you know and think it's awesome, we could include it (either with this PR or later). 
Cheers.

### CODE REVIEW

**Comment by koalive** [comment]
PS: There's one link to a collection of articles that I classified as "Review", hope it's good enough.

@jccaicedo do you think we should include DeepProfiler in the Software section or is it too early?

**Comment by gwaybio** [comment]
LGTM!

**Comment by lopaavol** [comment]
Here are some comments:
- Is HPA raw images downloadable from their site? Earlier those weren't available and I could not quickly find the images now either.

- Do we want to include preprints? I mean in the context of Awesome list. Not all papers, especially ML methodological papers, ever make their way into any journal or conference publication, and a paper can be awesome even if it is under review. Just wanted to raise a point if we draw the line somewhere.

- Deep learning in microscopy collection: I would maybe leave this out from Awesome list as it is not a review paper. Maybe the awesome method papers from that collection could be added separately.

- Later we might need to add some categories in "Methods"

**Comment by koalive** [comment]
Thanks for the feedback!

* I added a better link for the HPA. There's a server to download raw images but I only found the information in a repo from their Kaggle challenge. The trick also works with more recent releases of the data.
* I'm all for listing preprints, even if it probably requires to be even more careful to claim that they're relevant. A few are already listed and this PR would add a few more.
* I added a "Collections" section for it (and added another link). I like that it offers a good outlook of the ongoing research and provides a way to dive into more specific topics. Let's say I find these lists awesome, rather than all the individual articles. Would that be OK?

Cheers.

**Pull request merged**
